// api/index.js - BRONX OSINT V14 - RATE LIMIT + CUSTOM MESSAGES
const express = require('express');
const axios = require('axios');
const fs = require('fs');
const path = require('path');
const app = express();

const REAL_API_BASE = 'https://ft-osint-api.duckdns.org/api';
const REAL_API_KEYS = ['bronx-bot-9999', 'bronx-bot-9999', 'bronx', 'bronx'];
let currentKeyIndex = 0;
function getNextKey() { const key = REAL_API_KEYS[currentKeyIndex]; currentKeyIndex = (currentKeyIndex + 1) % REAL_API_KEYS.length; return key; }

const FAKE_IPS = ['103.15.224.' + Math.floor(Math.random()*255), '117.98.45.' + Math.floor(Math.random()*255), '152.67.89.' + Math.floor(Math.random()*255), '157.34.123.' + Math.floor(Math.random()*255), '182.76.55.' + Math.floor(Math.random()*255), '223.188.12.' + Math.floor(Math.random()*255)];
function getFakeIP() { return FAKE_IPS[Math.floor(Math.random() * FAKE_IPS.length)]; }

const ADMIN_USERNAME = process.env.ADMIN_USERNAME || 'BRONX_ULTRA';
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || 'king5';
const MASTER_API_KEY = process.env.MASTER_API_KEY || 'BRONX_MASTER_' + Math.random().toString(36).substring(2,10).toUpperCase();

const DATA_DIR = process.env.RENDER_DATA_DIR || '/tmp';
const DATA_FILE = path.join(DATA_DIR, 'bronx_v14_data.json');

let keyStorage = {};
let customAPIs = [];
let requestLogs = [];
let adminSessions = {};
let permanentTokens = {};
let protectedData = {};
let dailyLimits = {};

function saveToDisk(){try{const ks={};Object.entries(keyStorage).forEach(([k,v])=>{if(!v._hardcoded)ks[k]=v});const d={keys:ks,apis:customAPIs,tokens:permanentTokens,logs:requestLogs.slice(-500),protected:protectedData};fs.writeFileSync(DATA_FILE,JSON.stringify(d,null,2))}catch(e){}}
function loadFromDisk(){try{if(fs.existsSync(DATA_FILE)){const d=JSON.parse(fs.readFileSync(DATA_FILE,'utf8'));if(d.keys)Object.entries(d.keys).forEach(([k,v])=>{keyStorage[k]=v});if(d.apis?.length>0)customAPIs=d.apis;if(d.tokens){permanentTokens=d.tokens;Object.entries(permanentTokens).forEach(([t])=>{adminSessions[t]={expiresAt:Date.now()+(365*24*60*60*1000),permanent:true}})}if(d.logs)requestLogs=d.logs;if(d.protected)protectedData=d.protected;return true}}catch(e){}return false}
function scheduleSave(){setTimeout(()=>saveToDisk(),2000)}setInterval(()=>scheduleSave(),5*60*1000);

function getIndiaTime(){return new Date(new Date().getTime()+(5.5*60*60*1000))}
function getIndiaDate(){return getIndiaTime().toISOString().split('T')[0]}
function getIndiaDateTime(){return getIndiaTime().toISOString().replace('T',' ').substring(0,19)}
function isKeyExpired(d){if(!d||d==='LIFETIME')return false;return getIndiaTime()>new Date(d)}
function parseExpiryDate(s){if(!s||s==='LIFETIME')return null;const p=s.split('-');if(p.length===3)return p[0].length===4?new Date(+p[0],+p[1]-1,+p[2],23,59,59):new Date(+p[2],+p[1]-1,+p[0],23,59,59);const d=new Date(s);return isNaN(d.getTime())?null:d}
function checkDailyLimit(k){const kd=keyStorage[k];if(!kd||!kd.dailyLimit)return{allowed:true};const today=getIndiaDate();const dk=k+'_'+today;if(!dailyLimits[dk])dailyLimits[dk]=0;if(dailyLimits[dk]>=kd.dailyLimit)return{allowed:false,remaining:0,message:`🔴 Daily Limit ${kd.dailyLimit}/${kd.dailyLimit} Reached! Resets at 12 AM.`};return{allowed:true,used:dailyLimits[dk],remaining:kd.dailyLimit-dailyLimits[dk]}}
function isProtected(value){for(const key in protectedData){if(value.includes(protectedData[key]))return protectedData[key]}return null}

// ✅ CUSTOM MESSAGE FOR KEY NOT FOUND / LIMIT REACHED
const UPGRADE_MSG = `\n\n🛒 𝗣𝗨𝗥𝗖𝗛𝗔𝗦𝗘 𝗣𝗔𝗜𝗗 𝗔𝗣𝗜\n━━━━━━━━━━━━━━━━━━\n💎 Unlimited Access\n📅 30 Days = ₹300\n📅 60 Days = ₹600\n📅 100 Days = ₹999\n👑 Lifetime = ₹5000\n━━━━━━━━━━━━━━━━━━\n💬 𝗖𝗼𝗻𝘁𝗮𝗰𝘁 𝗔𝗱𝗺𝗶𝗻: @BRONX_ULTRA`;

function checkKeyValid(k){
    if(!k)return{valid:false,error:'❌ Missing API Key! Please provide a valid key.'+UPGRADE_MSG};
    const kd=keyStorage[k];
    if(!kd)return{valid:false,error:'🔑 𝗞𝗲𝘆 𝗡𝗼𝘁 𝗙𝗼𝘂𝗻𝗱!\n\n⚠️ This API key does not exist in our system.'+UPGRADE_MSG};
    if(kd.stopped)return{valid:false,error:'⛔ 𝗞𝗲𝘆 𝗦𝘁𝗼𝗽𝗽𝗲𝗱!\n\nYour API key has been deactivated by admin.'+UPGRADE_MSG};
    if(kd.expiry&&isKeyExpired(kd.expiry))return{valid:false,error:'⏰ 𝗞𝗲𝘆 𝗘𝘅𝗽𝗶𝗿𝗲𝗱 on '+kd.expiryStr+'\n\nYour API key validity has ended.'+UPGRADE_MSG};
    if(!kd.unlimited&&kd.used>=kd.limit)return{valid:false,error:`🔴 𝗟𝗜𝗠𝗜𝗧 𝗥𝗘𝗔𝗖𝗛𝗘𝗗!\n\n📊 ${kd.limit}/${kd.limit} Requests Used\n⚠️ Your API key limit is exhausted.`+UPGRADE_MSG};
    const dl=checkDailyLimit(k);
    if(!dl.allowed)return{valid:false,error:'🔴 𝗗𝗔𝗜𝗟𝗬 𝗟𝗜𝗠𝗜𝗧 𝗥𝗘𝗔𝗖𝗛𝗘𝗗!\n\n⚠️ Daily limit exhausted. Resets at midnight.'+UPGRADE_MSG};
    return{valid:true,keyData:kd};
}
function incrementKeyUsage(k){if(keyStorage[k]&&!keyStorage[k].unlimited){keyStorage[k].used++;const dk=k+'_'+getIndiaDate();if(!dailyLimits[dk])dailyLimits[dk]=0;dailyLimits[dk]++;if(keyStorage[k].used%10===0)scheduleSave()}}
function checkKeyScope(kd,ep){if(!kd?.scopes?.length)return{valid:false,error:'No scopes'};if(kd.scopes.includes('*'))return{valid:true};if(kd.scopes.includes(ep))return{valid:true};if(ep.startsWith('c/')&&kd.scopes.includes('custom'))return{valid:true};return{valid:false,error:`Scope denied. Required: ${ep}`}}
function generateToken(){const c='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';let t='';for(let i=0;i<32;i++)t+=c.charAt(Math.floor(Math.random()*c.length));return t}
function isAdminAuth(t){if(!t)return false;if(adminSessions[t]){if(adminSessions[t].permanent)return true;if(Date.now()<adminSessions[t].expiresAt)return true;delete adminSessions[t];delete permanentTokens[t]}return false}
function sanitizeResponse(d){if(!d)return d;try{const c=JSON.parse(JSON.stringify(d));delete c.credit;delete c.truecaller_name;delete c.cached;delete c.cached_at;delete c.api_by;delete c.by;delete c.channel;delete c.developer;delete c.api_key;delete c.real_url;delete c.source_url;delete c.owner;delete c.key_note;delete c.response_time_ms;if(c.meta){delete c.meta.api_by;delete c.meta.response_time_ms;delete c.meta.quota_used;if(Object.keys(c.meta).length===0)delete c.meta}c.powered_by="@BRONX_ULTRA";return c}catch(e){return d}}
function esc(s){if(!s)return'';return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
function createMasterKey(){return{name:'👑 OWNER',scopes:['*'],type:'owner',limit:999999,used:0,cooldown:0,dailyLimit:0,expiry:null,expiryStr:'LIFETIME',created:getIndiaDateTime(),unlimited:true,hidden:true,_hardcoded:false}}

function initHardcodedKeys(){const now=getIndiaDateTime();const hc=[{key:'BRONX_PREMIUM_V100_01',name:'Premium 01',limit:999999,expiry:'31-12-2028',scopes:['*']},{key:'BRONX_ULTRA_OSINT_01',name:'Ultra 01',limit:888888,expiry:'30-06-2029',scopes:['number','aadhar','upi','pan']},{key:'BRONX_KING_OP_V100',name:'King OP',limit:999999,expiry:'31-12-2030',scopes:['*']},{key:'BRONX_ELITE_V100_01',name:'Elite 01',limit:999999,expiry:'31-12-2030',scopes:['*']},{key:'BRONX_GOD_TIER_V100',name:'God Tier',limit:999999,expiry:'31-12-2030',scopes:['*']}];hc.forEach(d=>{if(!keyStorage[d.key])keyStorage[d.key]={name:d.name,scopes:d.scopes,type:'hardcoded',limit:d.limit,used:0,cooldown:0,dailyLimit:0,expiry:parseExpiryDate(d.expiry),expiryStr:d.expiry,created:now,unlimited:true,hidden:true,_hardcoded:true}})}
function initCustomAPIs(){customAPIs=[{id:1,name:'Number Info',endpoint:'number-advanced',param:'num',example:'9876543210',visible:true,realAPI:'https://num-tg-info-api.vercel.app/info?number={param}'},{id:2,name:'Vehicle RC',endpoint:'rc-details',param:'ca_number',example:'MH02FZ0555',visible:true,realAPI:'https://simple-rc-info.vercel.app/rc?num={param}'}]}
const endpoints={number:{p:'num',i:'📱',e:'9876543210',d:'Mobile Lookup',c:'phone'},aadhar:{p:'num',i:'🆔',e:'393933081942',d:'Aadhaar',c:'phone'},vehicle:{p:'vehicle',i:'🚗',e:'MH02FZ0555',d:'Vehicle',c:'vehicle'},upi:{p:'upi',i:'💰',e:'example@ybl',d:'UPI',c:'finance'},ifsc:{p:'ifsc',i:'🏦',e:'SBIN0001234',d:'IFSC',c:'finance'},pan:{p:'pan',i:'📄',e:'AXDPR2606K',d:'PAN',c:'finance'},pincode:{p:'pin',i:'📍',e:'110001',d:'Pincode',c:'location'},ip:{p:'ip',i:'🌐',e:'8.8.8.8',d:'IP Lookup',c:'location'},ff:{p:'uid',i:'🎮',e:'123456789',d:'Free Fire',c:'gaming'},bgmi:{p:'uid',i:'🎮',e:'5121439477',d:'BGMI',c:'gaming'},insta:{p:'username',i:'📸',e:'cristiano',d:'Instagram',c:'social'},tg:{p:'info',i:'📲',e:'JAUUOWNER',d:'Telegram',c:'social'},snap:{p:'username',i:'👻',e:'priyapanchal272',d:'Snapchat',c:'social'}};

app.use(express.json({limit:'50mb'}));app.use(express.urlencoded({extended:true,limit:'50mb'}));app.set('json spaces',2);
app.use((req,res,next)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type,x-api-key,x-admin-token');if(req.method==='OPTIONS')return res.status(200).end();req.clientIP='FAKE_'+getFakeIP();next()});

app.get('/',(req,res)=>{try{res.send(renderHome())}catch(e){res.send('Error')}});
app.get('/docs',(req,res)=>{try{res.send(renderDocs())}catch(e){res.send('Error')}});
app.get('/test',(req,res)=>{res.json({status:'✅ BRONX V14',endpoints:Object.keys(endpoints).length,total_keys:Object.keys(keyStorage).length})});
app.get('/api/custom/:ep',async(req,res)=>{try{const api=customAPIs.find(a=>a.endpoint===req.params.ep&&a.visible);if(!api)return res.json({error:'Not found'});const key=req.query.key;if(!key)return res.json({error:'Key required'+UPGRADE_MSG});const kc=checkKeyValid(key);if(!kc.valid)return res.json({error:kc.error});const sc=checkKeyScope(kc.keyData,'custom');if(!sc.valid)return res.json({error:sc.error});const pv=req.query[api.param]||req.query.number;if(!pv)return res.json({error:'Missing param'});const prot=isProtected(pv);if(prot)return res.json({error:'🔒 PROTECTED',protected:true});let url=api.realAPI.replace(/\{param\}/gi,encodeURIComponent(pv));const r=await axios.get(url,{timeout:30000});incrementKeyUsage(key);logReq(key,'c/'+req.params.ep,pv,'success');res.json({...sanitizeResponse(r.data),api_info:{key_owner:kc.keyData?.name,remaining:kc.keyData?.unlimited?'∞':Math.max(0,(kc.keyData?.limit||0)-(kc.keyData?.used||0))}})}catch(e){res.json({error:'API error'})}});
app.get('/api/key-bronx/:ep',async(req,res)=>{try{const ep=req.params.ep;if(!endpoints[ep])return res.json({error:'Not found'});const key=req.query.key;if(!key)return res.json({error:'Key required'+UPGRADE_MSG});const kc=checkKeyValid(key);if(!kc.valid)return res.json({error:kc.error});const sc=checkKeyScope(kc.keyData,ep);if(!sc.valid)return res.json({error:sc.error});const pv=req.query[endpoints[ep].p];if(!pv)return res.json({error:'Missing '+endpoints[ep].p});const prot=isProtected(pv);if(prot)return res.json({error:'🔒 PROTECTED',protected:true});const url=`${REAL_API_BASE}/${ep}?key=${getNextKey()}&${endpoints[ep].p}=${encodeURIComponent(pv)}`;const r=await axios.get(url,{timeout:30000});incrementKeyUsage(key);logReq(key,ep,pv,'success');res.json({...sanitizeResponse(r.data),api_info:{key_owner:kc.keyData?.name,remaining:keyStorage[key]?.unlimited?'∞':Math.max(0,(keyStorage[key]?.limit||0)-(keyStorage[key]?.used||0))}})}catch(e){res.json({error:'API error'})}});

function logReq(key,ep,param,status){const fakeIP=getFakeIP();requestLogs.push({timestamp:getIndiaDateTime(),key:key?key.substring(0,8)+'***':'?',endpoint:ep,param:param?param.substring(0,20):'',status,ip:fakeIP});if(requestLogs.length>500)requestLogs=requestLogs.slice(-500);if(requestLogs.length%10===0)scheduleSave()}

// ========== ADMIN ROUTES ==========
app.get('/admin',(req,res)=>{try{const token=req.query.token||req.headers['x-admin-token'];if(token&&isAdminAuth(token))return res.send(renderAdmin(token));res.send(renderLogin())}catch(e){res.send('Error')}});
app.post('/admin/login',async(req,res)=>{const{username,password}=req.body;if(username===ADMIN_USERNAME&&password===ADMIN_PASSWORD){const token=generateToken();adminSessions[token]={expiresAt:Date.now()+(365*24*60*60*1000),permanent:true};permanentTokens[token]={createdAt:getIndiaDateTime()};scheduleSave();res.json({success:true,token,message:'✅ Access Granted',redirect:'/admin?token='+token})}else res.json({success:false,error:'Invalid'})});
app.post('/admin/generate-key',async(req,res)=>{if(!isAdminAuth(req.headers['x-admin-token']||req.query.token))return res.json({e:'Unauthorized'});const{keyName,keyOwner,scopes,limit,expiryDate,days,dailyLimit}=req.body;if(!keyName||!keyOwner)return res.json({e:'Missing'});if(keyStorage[keyName])return res.json({e:'Exists'});const ks=scopes||['number'];let exp=null,es=expiryDate||'LIFETIME';if(days&&!isNaN(days)){const d=new Date(getIndiaTime().getTime()+parseInt(days)*24*60*60*1000);exp=d;es=d.toISOString().split('T')[0].split('-').reverse().join('-')}else if(expiryDate&&expiryDate!=='LIFETIME'){exp=parseExpiryDate(expiryDate);es=expiryDate}keyStorage[keyName]={name:keyOwner,scopes:ks,type:'generated',limit:parseInt(limit)||100,used:0,dailyLimit:parseInt(dailyLimit)||0,expiry:exp,expiryStr:es,created:getIndiaDateTime(),unlimited:false,hidden:false,_hardcoded:false};saveToDisk();res.json({success:true,key:keyName,scopes:ks,expiry:es,message:'🔑 Key Generated!'})});
app.post('/admin/import-key',async(req,res)=>{if(!isAdminAuth(req.headers['x-admin-token']||req.query.token))return res.json({e:'Unauthorized'});const{jsonData}=req.body;if(!jsonData)return res.json({e:'Missing JSON'});try{const data=typeof jsonData==='string'?JSON.parse(jsonData):jsonData;if(Array.isArray(data)){let count=0;data.forEach(k=>{if(k.key&&!keyStorage[k.key]){keyStorage[k.key]={name:k.name||k.key,scopes:k.scopes||['*'],type:'imported',limit:k.limit||100,used:k.used||0,dailyLimit:k.dailyLimit||0,expiry:k.expiryStr?parseExpiryDate(k.expiryStr):null,expiryStr:k.expiryStr||'LIFETIME',created:k.created||getIndiaDateTime(),unlimited:k.unlimited||false,hidden:false,_hardcoded:false};count++}});saveToDisk();res.json({success:true,imported:count})}else if(data.key){if(keyStorage[data.key])return res.json({e:'Exists'});keyStorage[data.key]={name:data.name||data.key,scopes:data.scopes||['*'],type:'imported',limit:data.limit||100,used:data.used||0,dailyLimit:data.dailyLimit||0,expiry:data.expiryStr?parseExpiryDate(data.expiryStr):null,expiryStr:data.expiryStr||'LIFETIME',created:data.created||getIndiaDateTime(),unlimited:data.unlimited||false,hidden:false,_hardcoded:false};saveToDisk();res.json({success:true,imported:1})}else{res.json({e:'Invalid format'})}}catch(e){res.json({e:'Invalid JSON'})}});
app.post('/admin/export-key',async(req,res)=>{if(!isAdminAuth(req.headers['x-admin-token']||req.query.token))return res.json({e:'Unauthorized'});const{keyName}=req.body;if(keyName){const kd=keyStorage[keyName];if(!kd)return res.json({e:'Not found'});res.json({success:true,exported:{key:keyName,name:kd.name,scopes:kd.scopes,limit:kd.limit,used:kd.used,dailyLimit:kd.dailyLimit||0,expiryStr:kd.expiryStr,created:kd.created,unlimited:kd.unlimited}})}else{const all=Object.entries(keyStorage).filter(([k,d])=>!d._hardcoded&&!d.hidden).map(([k,d])=>({key:k,name:d.name,scopes:d.scopes,limit:d.limit,used:d.used,dailyLimit:d.dailyLimit||0,expiryStr:d.expiryStr,created:d.created,unlimited:d.unlimited}));res.json({success:true,exported:all,count:all.length})}});
app.post('/admin/push-key',async(req,res)=>{if(!isAdminAuth(req.headers['x-admin-token']||req.query.token))return res.json({e:'Unauthorized'});const{keyName,days}=req.body;if(!keyStorage[keyName])return res.json({e:'Not found'});if(keyStorage[keyName]._hardcoded)return res.json({e:'Protected'});const d=parseInt(days)||30;const ne=new Date(getIndiaTime().getTime()+d*24*60*60*1000);keyStorage[keyName].expiry=ne;keyStorage[keyName].expiryStr=ne.toISOString().split('T')[0].split('-').reverse().join('-');keyStorage[keyName].used=0;saveToDisk();res.json({success:true,message:`⬆ Pushed ${d} days!`})});
app.post('/admin/delete-key',async(req,res)=>{if(!isAdminAuth(req.headers['x-admin-token']||req.query.token))return res.json({e:'Unauthorized'});if(req.body.keyName===MASTER_API_KEY||keyStorage[req.body.keyName]?._hardcoded)return res.json({e:'Protected'});delete keyStorage[req.body.keyName];saveToDisk();res.json({success:true})});
app.post('/admin/reset-all',async(req,res)=>{if(!isAdminAuth(req.headers['x-admin-token']||req.query.token))return res.json({e:'Unauthorized'});Object.keys(keyStorage).forEach(k=>{if(k!==MASTER_API_KEY&&!keyStorage[k]._hardcoded)keyStorage[k].used=0});dailyLimits={};saveToDisk();res.json({success:true})});
app.post('/admin/clear-logs',async(req,res)=>{if(!isAdminAuth(req.headers['x-admin-token']||req.query.token))return res.json({});requestLogs=[];saveToDisk();res.json({success:true})});
app.post('/admin/update-scopes',async(req,res)=>{if(!isAdminAuth(req.headers['x-admin-token']||req.query.token))return res.json({e:'Unauthorized'});const{keyName,scopes}=req.body;if(!keyStorage[keyName])return res.json({e:'Not found'});if(keyStorage[keyName]._hardcoded)return res.json({e:'Hardcoded'});keyStorage[keyName].scopes=scopes;saveToDisk();res.json({success:true})});
app.post('/admin/stop-key',async(req,res)=>{if(!isAdminAuth(req.headers['x-admin-token']||req.query.token))return res.json({e:'Unauthorized'});if(!keyStorage[req.body.keyName])return res.json({e:'Not found'});if(keyStorage[req.body.keyName]._hardcoded)return res.json({e:'Hardcoded'});keyStorage[req.body.keyName].stopped=!keyStorage[req.body.keyName].stopped;saveToDisk();res.json({success:true,stopped:keyStorage[req.body.keyName].stopped})});
app.post('/admin/add-api',async(req,res)=>{if(!isAdminAuth(req.headers['x-admin-token']||req.query.token))return res.json({e:'Unauthorized'});const{name,endpoint,param,example,realAPI}=req.body;if(!name||!endpoint)return res.json({e:'Missing'});customAPIs.push({id:customAPIs.length+1,name,endpoint,param:param||'num',example:example||'9876543210',visible:true,realAPI:realAPI||''});saveToDisk();res.json({success:true})});
app.post('/admin/toggle-api',async(req,res)=>{if(!isAdminAuth(req.headers['x-admin-token']||req.query.token))return res.json({e:'Unauthorized'});const api=customAPIs.find(a=>a.id===parseInt(req.body.id));if(api){api.visible=!api.visible;saveToDisk();res.json({success:true,visible:api.visible})}else res.json({e:'Not found'})});
app.post('/admin/delete-api',async(req,res)=>{if(!isAdminAuth(req.headers['x-admin-token']||req.query.token))return res.json({e:'Unauthorized'});const idx=customAPIs.findIndex(a=>a.id===parseInt(req.body.id));if(idx>-1){customAPIs.splice(idx,1);saveToDisk();res.json({success:true})}else res.json({e:'Not found'})});
app.post('/admin/add-protection',async(req,res)=>{if(!isAdminAuth(req.headers['x-admin-token']||req.query.token))return res.json({e:'Unauthorized'});const{value}=req.body;if(!value)return res.json({e:'Missing'});protectedData[value]=value;saveToDisk();res.json({success:true})});
app.post('/admin/remove-protection',async(req,res)=>{if(!isAdminAuth(req.headers['x-admin-token']||req.query.token))return res.json({e:'Unauthorized'});delete protectedData[req.body.value];saveToDisk();res.json({success:true})});
app.use((req,res)=>{res.json({error:'Not found'})});

// ========== PAGES ==========
function renderLogin(){return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>BRONX V14 | ULTRA</title><link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700;900&family=Rajdhani:wght@300;500;700&display=swap" rel="stylesheet"><style>
*{margin:0;padding:0;box-sizing:border-box}body{background:#000010;display:flex;justify-content:center;align-items:center;min-height:100vh;font-family:'Rajdhani',sans-serif;overflow:hidden}
.rb-orb{position:fixed;border-radius:50%;filter:blur(120px);animation:float 6s infinite;pointer-events:none;z-index:0}.rb-orb:nth-child(1){width:350px;height:350px;background:rgba(0,150,255,.15);top:-10%;left:-5%}.rb-orb:nth-child(2){width:300px;height:300px;background:rgba(139,0,255,.12);bottom:-10%;right:-5%;animation-delay:2s}.rb-orb:nth-child(3){width:250px;height:250px;background:rgba(255,0,128,.1);top:40%;left:50%;animation-delay:4s}@keyframes float{0%,100%{transform:translate(0,0)}33%{transform:translate(50px,-30px)}66%{transform:translate(-40px,40px)}}
.card{background:rgba(5,5,30,.85);padding:55px 45px;border-radius:28px;width:450px;position:relative;z-index:1;backdrop-filter:blur(60px);border:1px solid rgba(0,150,255,.1)}.card::after{content:'';position:absolute;inset:-2px;border-radius:30px;padding:2px;background:linear-gradient(135deg,#0096ff,#8b00ff,#ff0080,#ffb400,#00ff88,#0096ff);background-size:400% 400%;animation:borderRainbow 4s linear infinite;-webkit-mask:linear-gradient(#fff 0 0) content-box,linear-gradient(#fff 0 0);mask:linear-gradient(#fff 0 0) content-box,linear-gradient(#fff 0 0);-webkit-mask-composite:xor;mask-composite:exclude;pointer-events:none}@keyframes borderRainbow{0%{background-position:0% 50%}100%{background-position:400% 50%}}
.card .logo{text-align:center;font-family:'Orbitron',sans-serif;font-size:14px;letter-spacing:12px;background:linear-gradient(90deg,#0096ff,#8b00ff,#ff0080,#ffb400,#00ff88);background-size:300% 100%;-webkit-background-clip:text;-webkit-text-fill-color:transparent;margin-bottom:14px;font-weight:900;animation:rainbowText 3s linear infinite}@keyframes rainbowText{0%{background-position:0% 50%}100%{background-position:300% 50%}}
.card h2{color:#fff;text-align:center;font-size:34px;font-weight:900;font-family:'Orbitron',sans-serif}.card .sub{text-align:center;color:#444;font-size:12px;letter-spacing:6px;margin-bottom:35px}.card input{width:100%;padding:17px 20px;background:rgba(0,0,20,.7);border:1px solid rgba(0,150,255,.1);border-radius:16px;color:#fff;font-size:15px;outline:none;font-family:'Rajdhani',sans-serif;margin-bottom:16px}.card input:focus{border-color:#0096ff;box-shadow:0 0 40px rgba(0,150,255,.2)}.btn{width:100%;padding:18px;background:linear-gradient(135deg,#0096ff,#8b00ff,#ff0080,#ffb400);background-size:300% 300%;color:#fff;border:none;border-radius:16px;cursor:pointer;font-size:16px;font-weight:700;letter-spacing:6px;font-family:'Orbitron',sans-serif;animation:btnRainbow 3s ease infinite}.btn:hover{transform:translateY(-3px) scale(1.02)}@keyframes btnRainbow{0%{background-position:0% 50%}100%{background-position:300% 50%}}.msg{color:#ff0080;text-align:center;margin-top:14px;font-size:13px;display:none;font-weight:600}
</style></head><body><div class="rb-orb"></div><div class="rb-orb"></div><div class="rb-orb"></div><div class="card"><div class="logo">BRONX OSINT V14</div><h2>🌈 ULTRA ACCESS</h2><p class="sub">Rate Limit • Import/Export • Live Logs</p><input type="text" id="u" placeholder="USERNAME"><input type="password" id="p" placeholder="PASSWORD"><button class="btn" onclick="login()">AUTHENTICATE</button><p class="msg" id="msg"></p></div><script>async function login(){var u=document.getElementById('u').value,p=document.getElementById('p').value,m=document.getElementById('msg');if(!u||!p){m.style.display='block';m.style.color='#ffaa00';m.textContent='⚠ Fill all';return}m.style.display='block';m.style.color='#0096ff';m.textContent='🌈...';try{var r=await fetch('/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:u,password:p})});var d=await r.json();if(d.success){m.style.color='#00ff88';m.textContent='✓ '+d.message;setTimeout(()=>location.href=d.redirect,500)}else{m.style.color='#ff0080';m.textContent='✗ '+d.error}}catch(e){m.textContent='✗ Error'}}</script></body></html>`}

function renderAdmin(token){try{
const allKeys=Object.entries(keyStorage).filter(([k,d])=>!d._hardcoded&&!d.hidden).map(([k,d])=>({key:k,name:d.name||'?',limit:d.unlimited?'∞':d.limit,used:d.used||0,left:d.unlimited?'∞':Math.max(0,(d.limit||0)-(d.used||0)),dailyLimit:d.dailyLimit||0,expiry:d.expiryStr||'Lifetime',isExpired:d.expiry?isKeyExpired(d.expiry):false,scopes:d.scopes||[],created:d.created||'',stopped:d.stopped||false}));
const hcCount=Object.values(keyStorage).filter(k=>k._hardcoded).length;
const stoken=esc(token);
let keysHTML=allKeys.map(k=>{let s='ACTIVE',sc='#00ff88';if(k.stopped){s='STOPPED';sc='#ff8800'}if(k.isExpired){s='EXPIRED';sc='#ff0000'}else if(k.left==0){s='LIMIT';sc='#ff8800'}const sd=k.scopes.includes('*')?'ALL':k.scopes.slice(0,3).join(',')+(k.scopes.length>3?'..':'');return`<tr><td><code>${esc(k.key.substring(0,15))}${k.key.length>15?'..':''}</code></td><td>${esc(k.name)}</td><td>${k.limit}</td><td>${k.used}</td><td>${k.dailyLimit||'∞'}</td><td style="color:${k.left==0?'#ff0000':'#00ff88'}">${k.left}</td><td>${esc(k.expiry)}</td><td>${sd}</td><td style="color:${sc}">${s}</td><td>${esc(k.created||'')}</td><td style="text-align:center"><button class="ab a-g" onclick="exportKey('${esc(k.key)}')">📤</button><button class="ab a-y" onclick="pushKey('${esc(k.key)}')">⬆</button><button class="ab a-r" onclick="stopKey('${esc(k.key)}')">⛔</button><button class="ab a-r" onclick="deleteKey('${esc(k.key)}')">✕</button></td></tr>`}).join('');
const logsHTML=requestLogs.slice(-50).reverse().map(l=>`<tr><td>${(l.timestamp||'').substring(0,16)}</td><td>${l.key||'?'}</td><td>/${l.endpoint||'?'}</td><td style="color:${l.status==='success'?'#00ff88':'#ff0000'}">${l.status||'?'}</td><td>${l.ip||''}</td></tr>`).join('')||'<tr><td colspan="5">No logs</td></tr>';
const apiHTML=customAPIs.map(a=>`<tr><td>${a.id}</td><td>${esc(a.name)}</td><td><code>/${esc(a.endpoint)}</code></td><td>${esc(a.param)}</td><td style="color:${a.visible?'#00ff88':'#444'}">${a.visible?'👁 VISIBLE':'🙈 HIDDEN'}</td><td><button class="ab a-y" onclick="toggleAPI(${a.id})">${a.visible?'HIDE':'SHOW'}</button><button class="ab a-r" onclick="deleteAPI(${a.id})">✕</button></td></tr>`).join('');

return `<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>BRONX V14 | PANEL</title><link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700;900&family=Rajdhani:wght@300;400;500;600;700&display=swap" rel="stylesheet"><style>
:root{--bg:#000010;--sur:rgba(5,5,30,.8);--brd:rgba(0,150,255,.08);--txt:#d0d8f0}
*{margin:0;padding:0;box-sizing:border-box}body{background:var(--bg);color:var(--txt);font-family:'Rajdhani',sans-serif;font-size:13px;min-height:100vh}
body::before{content:'';position:fixed;inset:0;background:radial-gradient(ellipse at 50% -10%,rgba(0,150,255,.08),transparent 50%),radial-gradient(ellipse at 80% 90%,rgba(139,0,255,.06),transparent 50%);pointer-events:none;z-index:0}
::-webkit-scrollbar{width:3px}::-webkit-scrollbar-thumb{background:linear-gradient(#0096ff,#8b00ff,#ff0080);border-radius:10px}
.top{background:rgba(5,5,30,.9);border-bottom:1px solid var(--brd);padding:14px 24px;display:flex;justify-content:space-between;align-items:center;position:sticky;top:0;z-index:100;backdrop-filter:blur(60px)}
.top h1{font-family:'Orbitron',sans-serif;font-size:15px;letter-spacing:8px;background:linear-gradient(90deg,#0096ff,#8b00ff,#ff0080,#ffb400,#00ff88);background-size:300% 100%;-webkit-background-clip:text;-webkit-text-fill-color:transparent;font-weight:900;animation:rainbowText 3s linear infinite}@keyframes rainbowText{0%{background-position:0% 50%}100%{background-position:300% 50%}}
.tb{display:flex;gap:8px}.tb a{background:rgba(0,150,255,.05);color:var(--txt);border:1px solid rgba(0,150,255,.1);padding:8px 14px;border-radius:10px;font-size:10px;font-weight:600;text-decoration:none;transition:.3s}.tb a:hover{background:rgba(139,0,255,.1);border-color:#8b00ff}
.container{max-width:1500px;margin:0 auto;padding:20px;position:relative;z-index:1}
.stats-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(110px,1fr));gap:10px;margin-bottom:18px}
.stat-card{background:var(--sur);border:1px solid var(--brd);border-radius:16px;padding:16px 12px;text-align:center;backdrop-filter:blur(40px);transition:.3s}.stat-card:hover{transform:translateY(-3px);box-shadow:0 0 50px rgba(0,150,255,.1)}.stat-card .val{font-size:28px;font-weight:900;background:linear-gradient(135deg,#0096ff,#8b00ff);-webkit-background-clip:text;-webkit-text-fill-color:transparent;font-family:'Orbitron',sans-serif}.stat-card .lbl{font-size:8px;color:#444;text-transform:uppercase;letter-spacing:3px;margin-top:4px}
.tabs{display:flex;gap:6px;margin-bottom:14px;flex-wrap:wrap}.tab{padding:10px 18px;background:var(--sur);border:1px solid var(--brd);border-radius:10px;color:#555;cursor:pointer;font-size:11px;font-weight:600;transition:.3s}.tab:hover{border-color:#0096ff;color:#00d4ff}.tab.on{background:rgba(0,150,255,.06);border-color:#0096ff;color:#fff;box-shadow:0 0 40px rgba(0,150,255,.1)}
.panel{display:none}.panel.on{display:block}
.section{background:var(--sur);border:1px solid var(--brd);border-radius:18px;padding:20px;margin-bottom:16px;backdrop-filter:blur(40px)}.section h3{color:#fff;margin-bottom:12px;font-size:15px;font-weight:700;letter-spacing:2px;font-family:'Orbitron',sans-serif}
table{width:100%;border-collapse:collapse;font-size:10px}th{background:rgba(0,150,255,.03);color:#666;padding:10px 6px;text-align:left;font-size:9px;letter-spacing:2px;font-weight:600}td{padding:8px 6px;border-bottom:1px solid rgba(255,255,255,.01)}tr:hover td{background:rgba(0,150,255,.02)}
code{font-family:monospace;font-size:9px}
.ab{padding:5px 10px;font-size:10px;border-radius:6px;border:1px solid;cursor:pointer;font-weight:600;transition:.3s;background:transparent;font-family:'Rajdhani',sans-serif;margin:1px}.a-g{color:#00ff88;border-color:rgba(0,255,136,.2)}.a-g:hover{background:rgba(0,255,136,.05)}.a-r{color:#ff0080;border-color:rgba(255,0,128,.2)}.a-r:hover{background:rgba(255,0,128,.05)}.a-y{color:#ffb400;border-color:rgba(255,180,0,.2)}.a-y:hover{background:rgba(255,180,0,.05)}
.btn-ultra{padding:12px 28px;background:linear-gradient(135deg,#0096ff,#8b00ff,#ff0080,#ffb400);background-size:300% 300%;color:#fff;border:none;border-radius:12px;font-weight:700;font-size:12px;cursor:pointer;letter-spacing:2px;font-family:'Orbitron',sans-serif;animation:btnRainbow 3s ease infinite;transition:.3s}.btn-ultra:hover{transform:translateY(-2px) scale(1.03)}@keyframes btnRainbow{0%{background-position:0% 50%}100%{background-position:300% 50%}}
.fgrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:10px}.fgrid label{display:block;color:#555;font-size:9px;text-transform:uppercase;letter-spacing:2px;margin-bottom:4px}
.fgrid input,.fgrid select,.fgrid textarea{width:100%;padding:12px 14px;background:rgba(0,0,20,.6);border:1px solid var(--brd);border-radius:12px;color:#fff;font-size:12px;font-family:'Rajdhani',sans-serif;outline:none;transition:.3s}.fgrid textarea{min-height:100px;resize:vertical}.fgrid input:focus,.fgrid select:focus,.fgrid textarea:focus{border-color:#0096ff;box-shadow:0 0 30px rgba(0,150,255,.15)}
.scope-box{display:flex;flex-wrap:wrap;gap:6px;padding:10px;background:rgba(0,0,20,.4);border:1px solid var(--brd);border-radius:10px;max-height:120px;overflow:auto}.scope-box label{cursor:pointer;font-size:10px;color:#666}@media(max-width:768px){.stats-grid{grid-template-columns:repeat(2,1fr)}}
</style></head><body>
<div class="top"><h1>🌈 BRONX ULTRA V14</h1><div class="tb"><span style="color:#222;font-size:9px;font-family:monospace">${getIndiaDateTime()}</span><a href="/">🏠 HOME</a><a href="/docs">📚 DOCS</a></div></div>
<div class="container">
<div class="stats-grid"><div class="stat-card"><div class="val">${allKeys.length}</div><div class="lbl">Gen Keys</div></div><div class="stat-card"><div class="val">${hcCount}</div><div class="lbl">Hardcoded</div></div><div class="stat-card"><div class="val">${requestLogs.length}</div><div class="lbl">Total Reqs</div></div></div>
<div class="tabs"><div class="tab on" onclick="st('gen')">⚡ GEN</div><div class="tab" onclick="st('keys')">🔑 KEYS</div><div class="tab" onclick="st('import')">📥 IMPORT</div><div class="tab" onclick="st('export')">📤 EXPORT</div><div class="tab" onclick="st('logs')">📜 LIVE LOGS</div><div class="tab" onclick="st('scopes')">🎯 SCOPES</div><div class="tab" onclick="st('push')">⬆ PUSH</div><div class="tab" onclick="st('apis')">🔧 APIs</div><div class="tab" onclick="st('addapi')">➕ ADD API</div><div class="tab" onclick="st('settings')">⚙ SET</div></div>
<div class="panel on" id="panel-gen"><div class="section"><h3>⚡ GENERATE KEY</h3><div class="fgrid"><div><label>Key ID</label><input id="gk" placeholder="MY_KEY"></div><div><label>Owner</label><input id="go" placeholder="Name"></div><div><label>Total Limit</label><input id="gl" value="100" type="number"></div><div><label>Daily Limit (0=∞)</label><input id="gdl" value="0" type="number"></div><div><label>Days Valid</label><input id="gd" value="30" type="number"></div><div style="grid-column:1/-1"><label>🎯 Scopes</label><div class="scope-box"><label><input type="checkbox" value="*" id="scope-all" checked onchange="toggleAllScopes()"> 🌟 ALL</label>${Object.keys(endpoints).map(e=>`<label><input type="checkbox" value="${e}" class="scope-cb"> ${endpoints[e].i} ${e}</label>`).join('')}</div></div><div style="grid-column:1/-1"><button class="btn-ultra" onclick="gk()" style="width:100%">🚀 GENERATE</button></div></div></div></div>
<div class="panel" id="panel-keys"><div class="section"><h3>🔑 KEYS (${allKeys.length})</h3><div style="max-height:450px;overflow:auto"><table><tr><th>KEY</th><th>OWNER</th><th>LIMIT</th><th>USED</th><th>DAY</th><th>LEFT</th><th>EXPIRY</th><th>SCOPES</th><th>STATUS</th><th>CREATED</th><th>ACT</th></tr>${keysHTML}</table></div></div></div>
<div class="panel" id="panel-import"><div class="section"><h3>📥 IMPORT KEYS</h3><div class="fgrid"><div style="grid-column:1/-1"><label>Paste JSON</label><textarea id="importData" placeholder='{"key":"MY_KEY","name":"Owner","scopes":["*"],"limit":100}'></textarea></div><div style="grid-column:1/-1"><button class="btn-ultra" onclick="importKeys()" style="width:100%">📥 IMPORT</button></div></div></div></div>
<div class="panel" id="panel-export"><div class="section"><h3>📤 EXPORT KEYS</h3><div class="fgrid"><div><label>Key Name (empty=ALL)</label><input id="exportKeyName" placeholder="Leave empty for ALL"></div><div style="grid-column:1/-1"><button class="btn-ultra" onclick="exportKeys()" style="width:100%">📤 EXPORT</button></div><div style="grid-column:1/-1"><textarea id="exportResult" readonly style="min-height:150px;margin-top:10px"></textarea></div></div></div></div>
<div class="panel" id="panel-logs"><div class="section"><h3>📜 LIVE LOGS</h3><div style="max-height:450px;overflow:auto"><table><tr><th>TIME</th><th>KEY</th><th>EP</th><th>STATUS</th><th>IP</th></tr>${logsHTML}</table></div></div></div>
<div class="panel" id="panel-scopes"><div class="section"><h3>🎯 UPDATE SCOPES</h3><div class="fgrid"><div><label>Key Name</label><input id="sk" placeholder="KEY_NAME"></div><div style="grid-column:1/-1"><label>New Scopes</label><div class="scope-box"><label><input type="checkbox" value="*" id="scope-all2"> 🌟 ALL</label>${Object.keys(endpoints).map(e=>`<label><input type="checkbox" value="${e}" class="scope-cb2"> ${endpoints[e].i} ${e}</label>`).join('')}</div></div><div style="grid-column:1/-1"><button class="btn-ultra" onclick="updateScopes()" style="width:100%">🎯 UPDATE</button></div></div></div></div>
<div class="panel" id="panel-push"><div class="section"><h3>⬆ PUSH KEY</h3><div class="fgrid"><div><label>Key Name</label><input id="pk" placeholder="KEY_NAME"></div><div><label>Days</label><input id="pd" value="30" type="number"></div><div style="grid-column:1/-1"><button class="btn-ultra" onclick="pushK()" style="width:100%">⬆ PUSH</button></div></div></div></div>
<div class="panel" id="panel-apis"><div class="section"><h3>🔧 CUSTOM APIs (${customAPIs.length})</h3><div style="max-height:350px;overflow:auto"><table><tr><th>ID</th><th>NAME</th><th>EP</th><th>PARAM</th><th>STATUS</th><th>ACT</th></tr>${apiHTML}</table></div></div></div>
<div class="panel" id="panel-addapi"><div class="section"><h3>➕ ADD API</h3><div class="fgrid"><div><label>Name</label><input id="aname" placeholder="My API"></div><div><label>Endpoint</label><input id="aep" placeholder="my-api"></div><div><label>Param</label><input id="aparam" placeholder="num"></div><div><label>Example</label><input id="aex" placeholder="9876543210"></div><div style="grid-column:1/-1"><label>Real URL ({param})</label><input id="aurl" placeholder="https://api.com?param={param}"></div><div style="grid-column:1/-1"><button class="btn-ultra" onclick="addAPI()" style="width:100%">➕ ADD</button></div></div></div></div>
<div class="panel" id="panel-settings"><div class="section"><h3>⚙ SETTINGS</h3><button class="btn-ultra" onclick="resetAll()" style="width:100%;margin-bottom:10px">🔄 RESET ALL USAGE</button><button class="btn-ultra" onclick="clearLogs()" style="width:100%;margin-bottom:10px">🗑 CLEAR LOGS</button><button class="ab a-r" onclick="if(confirm('Delete ALL?'))deleteAllKeys()" style="width:100%;padding:12px">🗑 DELETE ALL KEYS</button></div></div>
</div>
<script>var TOKEN='${stoken}';
function st(n){document.querySelectorAll('.panel').forEach(p=>p.classList.remove('on'));document.querySelectorAll('.tab').forEach(t=>t.classList.remove('on'));document.getElementById('panel-'+n).classList.add('on');event.target.classList.add('on')}
function toggleAllScopes(){var cb=document.getElementById('scope-all');document.querySelectorAll('.scope-cb').forEach(s=>s.checked=cb.checked)}
async function ac(u,b){var o={method:b?'POST':'GET',headers:{'Content-Type':'application/json','x-admin-token':TOKEN}};if(b)o.body=JSON.stringify(b);var r=await fetch(u,o);return await r.json()}
async function gk(){var n=document.getElementById('gk').value.trim(),o=document.getElementById('go').value.trim();if(!n||!o){alert('Fill fields');return}var scopes=[];if(document.getElementById('scope-all').checked)scopes=['*'];else document.querySelectorAll('.scope-cb:checked').forEach(c=>scopes.push(c.value));var r=await ac('/admin/generate-key',{keyName:n,keyOwner:o,scopes:scopes,limit:document.getElementById('gl').value,dailyLimit:parseInt(document.getElementById('gdl').value)||0,days:parseInt(document.getElementById('gd').value)||30});r.success?(alert('✅ Key: '+n),location.reload()):alert('❌ '+(r.e||'Error'))}
async function importKeys(){var d=document.getElementById('importData').value.trim();if(!d){alert('Paste JSON');return}try{JSON.parse(d)}catch(e){alert('Invalid JSON!');return}var r=await ac('/admin/import-key',{jsonData:d});r.success?(alert(r.message),location.reload()):alert('❌ Error')}
async function exportKey(k){var r=await ac('/admin/export-key',{keyName:k});if(r.success){document.getElementById('exportResult').value=JSON.stringify(r.exported,null,2);st('export')}}
async function exportKeys(){var kn=document.getElementById('exportKeyName').value.trim();var r=await ac('/admin/export-key',kn?{keyName:kn}:{});if(r.success){document.getElementById('exportResult').value=JSON.stringify(r.exported,null,2)}}
async function pushKey(k){var d=prompt('Days?','30');if(!d)return;var r=await ac('/admin/push-key',{keyName:k,days:parseInt(d)});r.success?(alert('✅ '+r.message),location.reload()):alert('❌ Error')}
async function pushK(){var k=document.getElementById('pk').value.trim(),d=parseInt(document.getElementById('pd').value)||30;if(!k){alert('Enter key');return}var r=await ac('/admin/push-key',{keyName:k,days:d});r.success?(alert('✅ '+r.message),location.reload()):alert('❌ Error')}
async function stopKey(k){if(!confirm('⛔ Stop/Activate: '+k+'?'))return;var r=await ac('/admin/stop-key',{keyName:k});r.success?(alert(r.stopped?'⛔ Stopped':'✅ Activated'),location.reload()):alert('❌ Error')}
async function deleteKey(k){if(confirm('DELETE?')){await ac('/admin/delete-key',{keyName:k});location.reload()}}
async function updateScopes(){var k=document.getElementById('sk').value.trim();if(!k){alert('Enter key');return}var scopes=[];if(document.getElementById('scope-all2').checked)scopes=['*'];else document.querySelectorAll('.scope-cb2:checked').forEach(c=>scopes.push(c.value));var r=await ac('/admin/update-scopes',{keyName:k,scopes:scopes});r.success?(alert('✅ Updated'),location.reload()):alert('❌ Error')}
async function clearLogs(){if(confirm('Clear?')){await ac('/admin/clear-logs');location.reload()}}
async function resetAll(){if(confirm('Reset?')){await ac('/admin/reset-all');location.reload()}}
async function deleteAllKeys(){document.querySelectorAll('button').forEach(b=>{if(b.textContent==='✕')b.click()});setTimeout(()=>location.reload(),1000)}
async function addAPI(){var n=document.getElementById('aname').value.trim(),e=document.getElementById('aep').value.trim();if(!n||!e){alert('Fill name & endpoint');return}var r=await ac('/admin/add-api',{name:n,endpoint:e,param:document.getElementById('aparam').value,example:document.getElementById('aex').value,realAPI:document.getElementById('aurl').value});r.success?(alert('✅ Added!'),location.reload()):alert('❌ Error')}
async function toggleAPI(id){await ac('/admin/toggle-api',{id:id});location.reload()}
async function deleteAPI(id){if(confirm('Delete?')){await ac('/admin/delete-api',{id:id});location.reload()}}
</script></body></html>`}catch(e){return `<html><body style="background:#000010;color:#ff0080;padding:30px"><h1>ERROR</h1><p>${e.message}</p></body></html>`}}

function renderDocs(){return `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>V14 DOCS</title><link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700;900&family=Rajdhani:wght@400;500;600&display=swap" rel="stylesheet"><style>:root{--bg:#000010;--sur:rgba(5,5,30,.7);--txt:#d0d8f0}*{margin:0;padding:0}body{background:var(--bg);color:var(--txt);font-family:'Rajdhani',sans-serif}.ct{max-width:1100px;margin:20px auto;padding:20px}.hero{text-align:center;padding:20px}.hero h1{font-family:'Orbitron',sans-serif;font-size:28px;background:linear-gradient(90deg,#0096ff,#8b00ff,#ff0080);-webkit-background-clip:text;-webkit-text-fill-color:transparent}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:10px}.card{background:var(--sur);border:1px solid rgba(0,150,255,.08);border-radius:14px;padding:14px}.method{background:rgba(0,150,255,.15);color:#0096ff;padding:2px 8px;border-radius:4px;font-size:10px}.card b{color:#fff;font-size:14px;margin-left:6px}.card p{color:#555;font-size:10px}code{display:block;background:rgba(0,0,20,.5);color:#00d4ff;padding:6px;border-radius:4px;font-size:9px;margin:6px 0;font-family:monospace}</style></head><body><div class="ct"><div class="hero"><h1>API DOCS V14</h1></div><div class="grid">${Object.entries(endpoints).map(([n,e])=>`<div class="card"><span class="method">GET</span><b>/${n}</b><p>${e.d}</p><code>GET /api/key-bronx/${n}?key=KEY&${e.p}=${e.e}</code></div>`).join('')}</div></div></body></html>`}
function renderHome(){let cards='';Object.entries(endpoints).forEach(([n,e])=>{cards+=`<div class="ep" onclick="cp('${esc(n)}','${esc(e.p)}','${esc(e.e)}')"><span>${e.i}</span><b>/${esc(n)}</b><small>${e.d}</small><code>${e.p}=${e.e}</code></div>`});return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>BRONX OSINT V14</title><link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700;900&family=Rajdhani:wght@300;400;600;700&display=swap" rel="stylesheet"><style>
:root{--bg:#000010;--sur:rgba(5,5,30,.6);--brd:rgba(0,150,255,.06);--txt:#d0d8f0}
*{margin:0;padding:0;box-sizing:border-box}body{background:var(--bg);color:var(--txt);font-family:'Rajdhani',sans-serif;overflow-x:hidden;font-size:14px}
nav{position:sticky;top:0;z-index:1000;background:rgba(0,0,16,.9);border-bottom:1px solid var(--brd);padding:12px 24px;display:flex;justify-content:space-between;align-items:center;backdrop-filter:blur(40px)}
nav .logo{font-family:'Orbitron',sans-serif;font-size:14px;background:linear-gradient(90deg,#0096ff,#8b00ff,#ff0080);background-size:300% 100%;-webkit-background-clip:text;-webkit-text-fill-color:transparent;font-weight:900;animation:rainbowText 3s linear infinite}@keyframes rainbowText{0%{background-position:0% 50%}100%{background-position:300% 50%}}
nav a{color:#555;text-decoration:none;font-size:10px;font-weight:600}nav a:hover{color:#0096ff}
.hero{text-align:center;padding:50px 20px 20px}.hero h1{font-size:clamp(36px,8vw,64px);font-weight:900;background:linear-gradient(90deg,#0096ff,#8b00ff,#ff0080,#ffb400,#00ff88);background-size:400% 100%;-webkit-background-clip:text;-webkit-text-fill-color:transparent;animation:rainbowText 4s linear infinite;font-family:'Orbitron',sans-serif}
.container{max-width:1200px;margin:0 auto;padding:0 20px 40px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(230px,1fr));gap:10px}
.ep{background:var(--sur);border:1px solid var(--brd);border-radius:14px;padding:16px;cursor:pointer;border-top:2px solid #0096ff;transition:.3s;backdrop-filter:blur(30px)}.ep:hover{transform:translateY(-4px);box-shadow:0 20px 50px rgba(0,0,0,.6)}.ep span{font-size:20px}.ep b{font-size:14px;color:#fff}.ep small{font-size:9px;color:#555;display:block;margin:4px 0 8px}.ep code{font-size:8px;color:#0096ff;background:rgba(0,0,20,.5);padding:3px 6px;border-radius:4px;font-family:monospace}
footer{text-align:center;padding:20px;border-top:1px solid var(--brd)}footer .fb{font-size:16px;font-weight:900;background:linear-gradient(90deg,#0096ff,#8b00ff,#ff0080);-webkit-background-clip:text;-webkit-text-fill-color:transparent;font-family:'Orbitron',sans-serif}
</style></head><body><nav><a href="/" class="logo">🌈 BRONX V14</a><div><a href="/docs">DOCS</a> <a href="/admin">ADMIN</a></div></nav><header class="hero"><h1>BRONX OSINT V14</h1><p style="color:#444;font-size:12px">Rate Limit • Import/Export • Live Logs</p></header><div class="container"><div class="grid">${cards}</div></div><footer><p class="fb">BRONX OSINT V14 🌈</p></footer><script>var eps=${JSON.stringify(endpoints)};function cp(n,p,e){navigator.clipboard.writeText(location.origin+'/api/key-bronx/'+n+'?key=KEY&'+p+'='+e)}</script></body></html>`}

const PORT = process.env.PORT || 3000;
(async function(){initHardcodedKeys();if(!loadFromDisk()){if(customAPIs.length===0)initCustomAPIs()}if(!keyStorage[MASTER_API_KEY])keyStorage[MASTER_API_KEY]=createMasterKey();scheduleSave();app.listen(PORT,()=>{console.log('🌈 BRONX OSINT V14 ONLINE!');console.log('✅ Rate Limit ON - No IP Ban');console.log('📥 Import/Export Ready');console.log('🚀 PORT: '+PORT)})})();
module.exports = app;
